---
# tasks file for frontend
- name: Create a network
  community.docker.docker_network:
    name: "projeta"
- name: Start a container with the frontend and connect to network
  #community.docker.docker_container:
  docker_container:
    ports:
      - "80:80"
    volumes:
      - "/home/nini/Documents/projet/student-list/website:/var/www/html"
    env:
      USERNAME: "toto"
      PASSWORD: "python"
    name: ihm-projet-a
    image: "php:apache"
    networks: 
      - name: "projeta"    
