---
- hosts: server2
  become: true

  tasks:
    - name: Install git
      apt:
       name: git
       state: present
       update_cache: yes

    - name: Just get information about the repository whether or not it has already been cloned locally
      ansible.builtin.git:
        repo: 'https://github.com/diranetafen/student-list.git'
        dest: /home/nini/Documents/student-list
        clone: no
        update: no
      register: repo_exist

    - name: Clone the project to GitHub
      ansible.builtin.git:
        repo: "https://github.com/diranetafen/student-list.git"
        dest:  /home/nini/Documents/student-list
      when : 
        - repo_exist.changed == true

